### ISSUE TITLE
environnement ending with *

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#1]
I really enjoyed your gist (https://gist.github.com/Aerijo/5b9522530715e5be6e89fc012e9a72a8#hyperclick), so I am trying out the different packages suggested in it. I particulary like `hyperclick-latex` to access documentation, labels from references and so on, great work !!! I just noticed a small bug with the environnement ending with * (e.g. `equation*`), it gives me the following warning:
![capture d ecran 2018-01-23 a 15 31 21](https://user-images.githubusercontent.com/15056323/35281144-812ef032-0052-11e8-9465-803723256a5e.png)

**Comment by Aerijo** [comment]
Released fix
