### ISSUE TITLE
[Feature request] Collapse and expand sections on click

### ISSUE THREAD

**Issue by werunom** [Aerijo/hyperclick-latex#2]
Currently, latex in atom is missing foldability. Folding is very crucial for documents typed in latex since most of these documents are verbose (unlike programmes written in a coding language, which is by nature, succinct). For instance, this is doable (in a limited way though) for markdown documents, where the headers can be folded (using this [package](https://atom.io/packages/markdown-folding)). 

So, is it possible to collapse and unfold sections, subsections, etc.? Felt, among all the packages available, this feature request might fall under the scope of this package. 

Let me know what you think. Thanks again for this new package.

**Comment by Aerijo** [comment]
That's not really hyperclick, but I want folding too. I'm working on `wordcount-latex` today though, so I can't say when I'll try.

It should be possible though, as I can see the API has a [folding section](https://atom.io/docs/api/v1.23.3/TextEditor#instance-foldCurrentRow) for text editors. I'll have a look at the package you linked too.

**Comment by werunom** [comment]
I know that this feature is not directly related to this package's context. But this is the closest package I could find to raise this feature-request :D 

Will wait patiently for this. Thanks!

**Comment by Aerijo** [comment]
@werunom  ~I'm afraid I'll have to put this feature on hold indefinitely.~ _is what I was about to say_.

Then I realised that folding based on section is _very similar_ to word counting based on section. So I did some work, most of it being slightly repurposing my existing section finding function. Now the package `latex-wordcount` has code folding, if you go into settings and enable it (and restart Atom).

The reason I was going to not even try, is that some time this year we're expecting a new grammar parsing method. Called [`tree-sitter`](https://github.com/tree-sitter/tree-sitter), it claims to be a much better replacement to the existing regex based grammars. One feature of the new method is that it builds a 'tree' of the document, so it should be straightforward to implement syntax folding directly in core. 

Another thing it can do is parse minified files (which is impressive). This is relevant in LaTeX too, as it removes the need for a `maxTokensLimit` setting, which was the cause of some bad highlighting (like in the issue you raised on `language-latex`).

I'll likely be only doing bug fixes on `language-latex2e` now, as I try and develop a package that will work with `tree-sitter`.

**Comment by werunom** [comment]
Thanks @Aerijo ! Tested it once; I think there are some glitches. Will raise the specific issues in case you are interested in them. Otherwise, as you mention, if this is a temporary work-around, then we can wait till the new implementation is carried out. 
Excited about the new implementation of `tree-sitter`. Largely, by when all these overhauls might happen - some months or end of the year?

Bit held up now. Will use the folding option by next week and let you know of the problems, if any. Thanks for taking time for this! :)
