### ISSUE TITLE
Hyperclick and busy signal

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#5]
I noticed that you add `busy signal` to show when the package is searching for a reference for example. In my case, the button of busy signal stays orange, as if it was still searching, even when it is done.

**Comment by Aerijo** [comment]
Does it turn back to green eventually? I tend to get some delay between it finishing, and the signal returning to green myself. This was with a file structure like follows
```latex
% a.tex

\input{b.tex}

\ref{trial}
```

```latex
% b.tex
\input{c.tex}
```

```latex
% c.tex
\input{d.tex}
```

```latex
% d.tex
\input{e.tex}
```

```latex
% e.tex
\label{trial}
```

It did find the label though, and it eventually returns to the green state. If yours stays orange, could you please post a file structure that causes the error? It needn't be the actual files, just the contents, what commands are used to link them, etc.

**Comment by PierreMarchand20** [comment]
Well, I have a simpler example, where it finds the label but does not get back to the green state:

```latex
%main
\documentclass[a4paper,10pt]{report}

\begin{document}

\include{test_1}

\end{document}
```

```latex
%test_1
% !TEX root = ../main.tex
\label{trial}

\ref{trial}

```

May be because I use `include` ?

**Comment by Aerijo** [comment]
I don't know how I do it, but I always seem to miss the trivial cases.

**Comment by PierreMarchand20** [comment]
Well , it always works great at the end ;-) thank you again !

**Comment by PierreMarchand20** [comment]
Well, I noticed that busy signal history only shows research of references between different files. If you use `hyperlink-latex` to look up a reference which is in the same file, it does not appear. Also, I am not sure it turns in orange state because it is too fast. (Note that I do not mind, it is just for your information)

**Comment by Aerijo** [comment]
@PierreMarchand20 I did that intentionally, as same file match should be very fast. Then again, other file matching is also pretty fast.

**Comment by PierreMarchand20** [comment]
Oh ok nice 👍  it makes sense, thank you
