### ISSUE TITLE
Wrong file opened

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#7]
Using the usual structure : main.tex, structure/chapter1.tex with ` \include{structure/chapter1}` in main.tex, it opens structure/chapter1.aux instead of structure/chapter1.tex (if the .aux file exists, otherwise it opens the .tex file)

**Comment by Aerijo** [comment]
I forgot about those files. With no extension it was just getting the first possible name match, and I guess it was in alphabetical order.

I've released a patch to limit the guessing to `.tex`, `.bib`, and `.tikz` files for now. I'll look at it deeper another time, and work out exactly how Latex handles file imports for the various commands.
