### ISSUE TITLE
Not working with citation

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#9]
I got the following warning: `Could not find bib file: TypeError: Path must be a string. Received false`

Here's my structure again:
```
biblio.bib
main.tex
structure/chapter1.tex
```
And I cite something in chapter1.tex.

**Comment by Aerijo** [comment]
Found the problem, will release fix (for the error message). I'll need to work more to find the bib file itself though.

For reference, how is the bibliography reached from `chapter1.tex`? I've got some basic rules, but want to add to them to make it more reliable. Currently, it looks for
-  a `% !TeX bib = <path>` magic comment
-  a `\addbibresource` command
- the root file, and applies the two checks again on that.

As a temporary fix, try putting the `!TeX bib` magic comment in the root file.

**Comment by PierreMarchand20** [comment]
For the moment, it is added in the root document using `\bibliography{biblio}`.

FYI, the magic comment trick works. By the way, I just noticed that I do not have syntax coloring in `.bib` file, is it normal ? (I am using `language-latex2e`)

**Comment by Aerijo** [comment]
Yeah, I never got round to that. Switching back to `language-latex` will give you it though. It shouldn't affect how any of my other packages work, except for a weird thing with how `language-latex` scopes file paths (that may affect autocompletion; and possibly hyperclick).

FYI, I am actually working on a tree-sitter version of it right now. It's currently holidays, so I have time to learn it properly and start on the latex one too.

**Comment by PierreMarchand20** [comment]
Since I am using `biblatex` now, my `\bibliography` call is not in the root document anymore so I will stick with the magic comment (which is really convenient). 

But I noticed a similar bug as you mentioned in #6 for `\usepackage`. When I do multiple citations with commas in one call (e.g. `\cite{Foo,Bar}`), it does not work since it looks for a `Foo,Bar` bibitem.

**Comment by Aerijo** [comment]
To be honest, I've hardly every used the `include`, `cite`, etc. commands. And when I have, I've always kept it to one per call.

So I didn't even know that one was comma-seperable. This patch makes both `cite` and `ref` like commands comma seperable, and I'll look into the proper handling if I get time.

**Comment by PierreMarchand20** [comment]
If you write a thesis or an article one day, they are quite useful commands :-) `\cite` with commas allows to compress several citations from one author for example. For `\include`, it helps getting a modular structure of your document (and makes it faster to compile https://tex.stackexchange.com/questions/246/when-should-i-use-input-vs-include), but I admit that I do not see the advantage to use it with commas (except that you get less lines of code).

**Comment by BambOoxX** [comment]
I have a similar problem.  It is in a thesis, so as @PierreMarchand20, I have multiple file nesting levels.
Basically, I have a `main` file loading a `header` containing among other things my bibliography.
Hence I have in my `main`
```
\input{configuration/header}
```
and in my `header`
```
\addbibresource{auxiliaires/bibliography.bib}
```
this throws a 
> Could not find bib file 

error.
In the same manner, when trying hyperclicks with `\includegraphics{}` calls, i also get an error.
Basically the file path is just wrong, 
To illustrate, let's say I have my `main` calling `chapter1` located in an `inputs` directory stored in my main folder. And that `chapter1` tries to include a `fig1` file stored in `pictures/chapter1`, where pictures is also stored in the main folder.
The contents of each file is then
In `main.tex`
```
\input{inputs/chapter1}
```
In `chapter1.tex`
```
\includegraphics{pictures/chapter1/fig1}
```
In this case, the path that is being built by the `latex-hyperclick` module is 
> absolutepathtomainfolder/inputs/chapter1/pictures/chapter1/fig1

So in a way, the module always refer to the file where the `\includegraphics` is located, while it should be the file being compiled at the time. 
Hope this helps !

**Comment by BambOoxX** [comment]
@Aerijo, did you have time to have a look at my previous comment ?

**Comment by Aerijo** [comment]
Yeah, I just don't have time to do anything at the moment.

**Comment by sbrl** [comment]
Hey, this package is awesome! Since the README said that clicking references was still only "planned", I wasn't too hopeful. However, this does seem to work as intended. I've found though that I need to put

```latex
% !TeX bib = ../report.bib
```
in every file though in order for `\cite`/`\citep` to work, because it doesn't recognise the root file (even when i have it open in another tab).
